jobs:
  build:
    docker:
      - image: cimg/base:stable                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: echo "This is a build step"          # similar to "script" in GitLab

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "This is a test step"

  integration:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail                 # Even if the job fails, continue to the next stages
  nuclei:
    machine: true
    steps:
      - checkout

      - run: |
          docker run --user $(id -u):$(id -g) -w /nuclei -v $(pwd):/nuclei:rw --rm projectdiscovery/nuclei:v2.9.6 -u https://prod-mtzm6aso.lab.practical-devsecops.training -j -o nuclei-output.json

      - store_artifacts:
          path: nuclei-output.json
          destination: nuclei-artifact

  prod:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "This is a deploy step"

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build
      - integration:
          requires:
            - test
      - nuclei:
          requires:
            - integration
      - prod:
          type: approval
          requires:
            - nuclei
